# config.yml ----------------------------------------------------------------- #
# Author: Louis Trocellier
# Description: Configuration parameters, paths, and environment settings.

default:
  paths:
    functions: "function"
    notebooks: "notebooks"
    data: "data"
    outputs: "outputs"
  project:
    name: "Adhoc Template"
    version: "0.1.0"
    author: "Louis Trocellier"
